### ISSUE TITLE
failed to download state: no nodes and missing file

### ISSUE THREAD

**Issue by vincentwardhana33** [ton-blockchain/ton#8] opened 2019-09-10 08:26 UTC
Running in Ubuntu 16
2 Processors, 8gb RAM

Got this error log after running
`./validator-engine --db /var/ton-work/db -C /var/ton-work/etc/ton-global.config.json  -l /var/ton-work/log`

```
[ 2][t 7][1568102046.292000294][download-state.cpp:227][!downloadstatereq]	failed to download state : [Error : 651 : no nodes]
[ 1][t 7][1568102184.351877928][files-async.hpp:90][!read file]	missing file /var/ton-work/db/static//E5BE87B69929738BB805BCC7386B57852B8167E7A12580D4ED3E1BB4A5ED29AA
```

**Comment by D4rk4** [comment] 2019-09-10 09:06
Same problem, builded from archive.

**Comment by koinov** [comment] 2019-09-10 12:23
Most likely this brings to node crash only in case there's no root block.  This happens because logger called in UNREACHABLE() method tries accessing to process that is already traced by another process, so ptrace throws the exception leading to main thread stops.  

Can be reproduced in Test-ton-collator 

[ 1][t 5][1568117669.311018705][files-async.hpp:90][!read file]	missing file /var/ton-work/db//static//0000000000000000000000000000000000000000000000000000000000000000
[ 0][t 5][1568117669.311090708][manager-disk.cpp:811][!manager]	Check `Unreachable` failed
Signal: SIGABRT (Aborted)
[pid 17525] [time 1568117671] Signal: 6
Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
warning: process 17525 is already traced by process 17523
ptrace: Operation not permitted.

**Comment by votetake** [comment] 2019-09-10 14:44
Created missed file, but this did not solve the problem :)

`[ 2][t 7][1568126176.960005522][download-state.cpp:227][!downloadstate]	failed to download state : [Error : 621 : bad zero state: file hash mismatch]`

**Comment by vincentwardhana33** [comment] 2019-09-13 07:31
is there any way to produce this missing file
/var/ton-work/db/static/E5BE87B69929738BB805BCC7386B57852B8167E7A12580D4ED3E1BB4A5ED29AA

**Comment by begetan** [comment] 2019-09-13 08:19
@ljk662 you only need to configure **"control"** section of the config.json file
The other parts should be created automatically after the initial run. If not - try to delete config.json file and repeate the whole procedure according to the How-To

**Comment by ton-blockchain** [comment] 2019-09-14 14:54
Error "failed to download state : [Error : 651 : no nodes]" usually means that network is not working at all and not even one TON Network node is accessible - i.e., you do not have a public IPv4 address, or the UDP port you have specified is blocked by your firewall.

**Comment by immartian** [comment] 2019-09-19 16:43
no lucks, anyone solved?

**Comment by sorokinvld** [comment] 2019-09-23 09:57
same problem

**Comment by immartian** [comment] 2019-09-23 10:34
I've made it work at last by restarting the process using `root` privilege to execute every step instructed in "HOW-TO".

**Comment by begetan** [comment] 2019-09-25 15:49
As I investigated, for now, this message appears if you do not fill out 2 sections of the config.json

` "addrs" : [ 
],`

This part should be initialized by the first run of the validator with the parameter `--ip <IP>:<PORT>`

The second part is the key section of the config:
`"control" : [
]`

You should add a proper configuration here:

```"control" : [
  { "id" : "bp/RCfduCLVxBEXHLSxf7eBKljV9qk7A3a6gJe06w/c=",
    "port" : <CONSOLE-PORT>,
    "allowed" : [
      { "id" : "i7pPj818xO9XO5/0jcY7ISqOkpK4H8A1m127hxnERlY=",
        "permissions" : 15
      }
    ]
  }
],```

This issue should be fixed in better error handling in the configuration parsing.

**Comment by lxgn** [comment] 2019-09-25 19:22
Does not help

[ 1][t 4][1569439247.745670795][files-async.hpp:90][!read file] missing file /var/ton-work/db//static//7A1F72BDE4B3D6A31D27B98EB0EF88F87EFB8E42EBF4DA40B8492826EB1E5C1A
[ 4][t 6][1569439247.745970011][download-state.cpp:56][!downloadstatereq][&FULL_NODE_DEBUG]     failed to download state [ w=-1 s=9223372036854775808 seq=0 VCSXxDHhTALFxReyTZRd8E4Ya3ySOmpOWAS4rBX9XBY= eh9yveSz1qMdJ7mOsO+I+H77jkLr9NpAuEkoJuseXBo= ]from AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=: [Error : 651 : no nodes]
[ 2][t 6][1569439247.746009588][download-state.cpp:227][!downloadstatereq]      failed to download state : [Error : 651 : no nodes]
[ 0][t 4][1569439248.687602043][dht.cpp:515][!localid]  Check `node.addr_list().size() > 0` failed

**Comment by lxgn** [comment] 2019-09-25 19:39
copying keyring and padding control don't help

**Comment by begetan** [comment] 2019-09-25 20:58
Please verify that you are using the latest build. If your node doesn't crash but still have warnings in logs like ` [Error : 651 : no nodes]` you just need to wait sometime. In my case, it took up to 1 minute to catch up the Network.

Finally, I've prepared fully automate building receipt for Ubuntu 18.04 so you can just run a script which will produce everything.

https://github.com/awesome-nodes/ton

**Comment by sorokinvld** [comment] 2019-09-30 11:50
same errors, nothing helps

**Comment by momaee** [comment] 2020-02-10 13:44
I have the same problem. In my country, Telegram and almost all its related sites and IP addresses are filtered.
I did all the above, but it doesn't work.
There are two errors:
failed to download state : [Error : 651 : no nodes]
failed to download state : [Error : 652 : adnl query timeout]
I run a UDP OpenVPN but it has no effect.

**Comment by momaee** [comment] 2020-02-15 10:32
I did this procedure and it worked. 
1 - running the full node
2 -  connecting the VPN
3- disconnecting the VPN
sometimes it is necessary to do steps 2 and 3 several times. 
Finally, the client will keep going on without any VPN.

**Comment by EmelyanenkoK** [comment] 2022-05-29 11:57
Problems should be solved with current codebase

**Closed by EmelyanenkoK** 2022-05-29 11:57 UTC
