### ISSUE TITLE
Endless transactions

### ISSUE THREAD

**Issue by vanasprin** [ton-blockchain/ton#28] opened 2019-09-24 16:58 UTC
Video bug report:
https://www.youtube.com/watch?v=Lbr3cNljEjo

After multiply sending files with the transfer of funds the wallet becomes empty. The transactions are not executed. I think that the grams are spent on the validators fees. Validators do not complete gram transfer transactions due to lack of funds and burn the balance on the wallet to 0. I suppose that the transaction should not be performed with insufficient account balance.

Address: 0QA-LQA38JxS2CNiWNO1he24ZyGpNexybr--m_ua8EMvFk06
Final balance: 863 nanograms

**Comment by ton-blockchain** [comment] 2019-09-27 09:08
Should already be fixed.

Was caused by a bug in `wallet.fif`. The message has been sent with flag 1.
1. The message was accepted because it had a correct signature and `seqno`
2. Storage fee has been applied.
3. Sum of storage fee and transferred funds was greater than the balance of the wallet. So transaction was aborted.
4. Because the flag was 1, the state of the wallet has not been changed. So `seqno` stayed the same.
5. Validators were able to apply the same message multiple times because `seqno` was still the same.

In the current version on `wallet.fif` flag 3 is already used.
In this case, such transaction will still fail, but `seqno` will be changed afterward. So it will fail only once.
https://github.com/ton-blockchain/ton/blob/master/crypto/smartcont/wallet.fif#L38

**Comment by vanasprin** [comment] 2019-09-27 17:06
Checked, indeed fixed!
Thank you for the quick response, I will continue to test further. I heard there's going to be a bug bounty on your telegram channel. It will be great if this issue will be counted for me.

**Closed** 2019-09-27 17:09 UTC
